/**
 * @jest-environment jsdom
 */

/*!
 * Copyright (c) 2026 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

import React from 'react';
import { act } from 'react-dom/test-utils';
import { createRoot } from 'react-dom/client';
import { Provider } from 'react-redux';
import { createStore } from 'redux';

import PipelineStrip from './PipelineStrip';
import goldenView from './__fixtures__/pipeline-view.golden.json';
import { formatDay, formatWhen } from '../../../utils/pipeline-strip';

// The viewer's Planka language, which a test may change.
let mockLanguage = 'en-US';

// Keys come back with their values, so a test can read what was counted.
jest.mock('react-i18next', () => {
  const t = (key, values) =>
    values && typeof values === 'object' ? `${key}${JSON.stringify(values)}` : key;

  return {
    useTranslation: () => [t, { language: mockLanguage }],
  };
});

jest.mock('react-beautiful-dnd', () => ({
  DragDropContext: (props) => props.children,
  Droppable: (props) =>
    props.children({ innerRef: () => {}, droppableProps: {}, placeholder: null }, {}),
  Draggable: (props) =>
    props.children(
      { innerRef: () => {}, draggableProps: {}, dragHandleProps: {} },
      { isDragging: false },
    ),
}));

jest.mock('../../../lib/popup', () => ({
  usePopup: () => (props) => props.children,
}));

jest.mock('react-hot-toast', () => ({
  __esModule: true,
  default: () => {},
}));

jest.mock('../../../selectors', () => ({
  __esModule: true,
  default: {
    selectCurrentUser: () => ({ id: 'user-1', name: 'Deniss', username: 'deniss' }),
  },
}));

jest.mock('../../../lib/redux-router', () => ({
  push: (to) => ({ type: 'router-push', payload: { to } }),
}));

window.IS_REACT_ACT_ENVIRONMENT = true;

const BOARD_ID = goldenView.boardId;

// Durations as the strip prints them under the mocked translation, whose unit
// letters come back as their keys: dur(14, 'm', 0, 's') is 14m 00s.
const UNIT_KEYS = {
  d: 'pipeline.unitDays',
  h: 'pipeline.unitHours',
  m: 'pipeline.unitMinutes',
  s: 'pipeline.unitSeconds',
};
const dur = (a, ua, b, ub) => `${a}${UNIT_KEYS[ua]} ${String(b).padStart(2, '0')}${UNIT_KEYS[ub]}`;
// The answer's own clock: every duration below is measured against it.
const NOW = goldenView.now;

let container;
let root;
let store;
let dispatchedActions;
let getAnswer;

const jsonResponse = (status, body) => ({
  ok: status >= 200 && status < 300,
  status,
  json: () => Promise.resolve(body),
});

// The answer the orchestrator actually writes: a populated view marshalled by
// its own GET /pipeline handler, generated by and asserted against
// devteam-orchestrator's TestAPopulatedPipelineViewMarshalsToTheGolden
// (internal/cardterm/pipelinegolden_test.go), whose
// TestPlankasPipelineFixtureIsTheGolden holds this copy byte for byte. A
// renamed json tag there fails that test rather than silently blanking a
// column here. Never edit it by hand: regenerate it on the Go side and copy
// it over.
const golden = () => JSON.parse(JSON.stringify(goldenView));

const deploys = () => golden().deploys;
const accounts = () => golden().accounts;

const view = (overrides = {}) => ({ ...golden(), ...overrides });

const flush = async () => {
  await act(async () => {
    await new Promise((resolve) => {
      setTimeout(resolve, 0);
    });
  });
};

const renderStrip = async () => {
  act(() => {
    root.render(
      <Provider store={store}>
        <PipelineStrip boardId={BOARD_ID} />
      </Provider>,
    );
  });

  await flush();
};

const click = (element) => {
  act(() => {
    element.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
  });
};

const chipText = (name) => {
  const chip = container.querySelector(`[data-chip="${name}"]`);
  return chip && chip.textContent;
};

const panel = (name) => container.querySelector(`[data-tab-panel="${name}"]`);

const openTab = async (name) => {
  click(container.querySelector(`[role="tab"][data-tab="${name}"]`));
  await flush();
};

beforeEach(() => {
  localStorage.clear();
  jest.useFakeTimers({ doNotFake: ['setTimeout', 'clearTimeout'], now: Date.parse(NOW) });

  getAnswer = () => jsonResponse(200, view());
  global.fetch = jest.fn(() => Promise.resolve(getAnswer()));

  dispatchedActions = [];
  store = createStore((state, action) => {
    dispatchedActions.push(action);
    return state || {};
  });

  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
});

afterEach(() => {
  act(() => {
    root.unmount();
  });

  container.remove();
  delete global.fetch;
  jest.useRealTimers();
});

describe('the collapsed header', () => {
  test('counts the test stages running and waiting, and the deployments', async () => {
    await renderStrip();

    expect(chipText('tests')).toBe('pipeline.testsChip{"running":2,"waiting":1}');
    expect(chipText('deploys')).toBe('pipeline.deploysChip{"count":1}');
    expect(container.querySelector('[data-chip="deploys"]').getAttribute('title')).toBe(
      'pipeline.deploysChipTitle{"deploying":1,"waiting":2}',
    );
  });

  test('shows a red chip naming an account at its usage limit', async () => {
    await renderStrip();

    const chip = container.querySelector('[data-chip="limited"]');
    expect(chip.textContent).toBe('⛔ pipeline.limitedChip{"names":"claude-b"}');
    expect(chip.className).toContain('chipRefused');
  });

  test('shows no red chip while no account is limited', async () => {
    getAnswer = () =>
      jsonResponse(200, view({ accounts: accounts().map((a) => ({ ...a, limited: false })) }));

    await renderStrip();

    expect(container.querySelector('[data-chip="limited"]')).toBeNull();
  });

  test('an orchestrator that predates the tabs draws the old header and no tabs', async () => {
    localStorage.setItem('planka_pipelineStrip_expanded', 'true');
    getAnswer = () =>
      jsonResponse(200, view({ tests: undefined, deploys: undefined, accounts: undefined }));

    await renderStrip();

    expect(container.querySelector('[data-chip="tests"]')).toBeNull();
    expect(container.querySelector('[data-chip="deploys"]')).toBeNull();
    expect(container.querySelector('[role="tablist"]')).toBeNull();
    expect(
      container.querySelectorAll('[data-thread], [data-pipeline-strip="ok"]'),
    ).not.toHaveLength(0);
  });
});

describe('expanded', () => {
  beforeEach(() => {
    localStorage.setItem('planka_pipelineStrip_expanded', 'true');
  });

  test('offers Build, Testing, Deployment, Accounts and Statistics, and opens on Build', async () => {
    await renderStrip();

    const tabs = [...container.querySelectorAll('[role="tab"]')];
    expect(tabs.map((tab) => tab.getAttribute('data-tab'))).toEqual([
      'build',
      'testing',
      'deployment',
      'accounts',
      'statistics',
    ]);
    expect(tabs[0].getAttribute('aria-selected')).toBe('true');
    // The Build tab is the strip as it was: the threads and the queue toggle.
    expect(container.querySelector('[data-tab-panel]')).toBeNull();
    expect(container.textContent).toContain('pipeline.queueTitle');
  });

  test('Build: draws the threads, held card, drain and queue from the keys the orchestrator sends', async () => {
    await renderStrip();

    // The overflow thread runs a job, so it counts as busy by its jobId
    // whatever its state; the limited one does not.
    expect(chipText('threads')).toBe('pipeline.threadsBusy{"busy":2,"total":3}');
    expect(chipText('queue')).toBe('pipeline.queueCount{"count":3}');
    expect(chipText('paused')).toBe('⏸ pipeline.pausedCount{"count":1}');
    expect(chipText('draining')).toBe('pipeline.draining');

    const busy = container.querySelector('[data-thread="CA1"]');
    expect(busy.textContent).toContain('Threaded ticket');
    expect(busy.textContent).toContain('37%');
    expect(busy.textContent).toContain('3/8');
    expect(busy.textContent).toContain('In Development · Dev');
    // stageStart is an hour before the answer's now, pipelineStart three.
    expect(busy.textContent).toContain(dur(1, 'h', 0, 'm'));
    expect(busy.textContent).toContain(dur(3, 'h', 0, 'm'));
    expect(busy.className).toContain('threadPaused');

    const overflow = container.querySelector('[data-thread="CA2"]');
    expect(overflow).not.toBeNull();
    expect(overflow.textContent).toContain('Question ticket');
    expect(container.querySelector('[data-thread="CB1"]')).toBeNull();

    expect(container.querySelector('[data-paused-row]').textContent).toContain(
      `alice · ${dur(10, 'm', 0, 's')}`,
    );
    expect(container.querySelector('[data-drain-status]').textContent).toContain(
      `pipeline.drainingSince{"actor":"deniss","age":"${dur(30, 'm', 0, 's')}"}`,
    );

    const toggle = [...container.querySelectorAll('button[aria-expanded]')].find((button) =>
      button.textContent.includes('pipeline.queueTitle'),
    );
    if (toggle.getAttribute('aria-expanded') !== 'true') {
      click(toggle);
    }
    const jobs = [...container.querySelectorAll('[data-job]')];
    expect(jobs.map((job) => job.getAttribute('data-job'))).toEqual([
      'job-q-1',
      'job-q-p',
      'job-q-2',
    ]);
    expect(jobs[0].textContent).toContain('Very High');
    expect(jobs[2].textContent).toContain(dur(25, 'm', 0, 's'));
  });

  test('remembers the last tab opened, across a reload', async () => {
    await renderStrip();
    await openTab('deployment');

    expect(panel('deployment')).not.toBeNull();
    expect(localStorage.getItem('planka_pipelineStrip_tab')).toBe('deployment');

    act(() => {
      root.unmount();
    });
    root = createRoot(container);
    await renderStrip();

    expect(panel('deployment')).not.toBeNull();
    expect(container.querySelector('[data-tab="deployment"]').getAttribute('aria-selected')).toBe(
      'true',
    );
  });

  test('a remembered tab the orchestrator cannot fill falls back to Build without forgetting it', async () => {
    localStorage.setItem('planka_pipelineStrip_tab', 'accounts');
    getAnswer = () => jsonResponse(200, view({ accounts: undefined }));

    await renderStrip();

    expect(panel('accounts')).toBeNull();
    expect(container.textContent).toContain('pipeline.queueTitle');
    expect(localStorage.getItem('planka_pipelineStrip_tab')).toBe('accounts');
  });

  test('Testing: each stage in flight, grouped by card, and the recently finished', async () => {
    await renderStrip();
    await openTab('testing');

    const testing = panel('testing');
    expect(testing.textContent).toContain('pipeline.testsSummary{"running":2,"waiting":1,"max":3}');

    const cards = [...testing.querySelectorAll('[data-test-card]')];
    expect(cards.map((card) => card.getAttribute('data-test-card'))).toEqual(['card-1', 'card-2']);
    expect(cards[1].querySelectorAll('[data-stage]')).toHaveLength(2);

    const waiting = testing.querySelector('[data-stage="setl:unit"]');
    expect(waiting.getAttribute('data-status')).toBe('queued');
    expect(waiting.textContent).toContain('pipeline.testWaiting{"max":3}');
    expect(waiting.querySelector('[data-profile="scoped"]').textContent).toBe(
      'pipeline.profileScoped',
    );
    // Waiting 14 minutes, counted from when it started waiting.
    expect(waiting.textContent).toContain(dur(14, 'm', 0, 's'));
    expect(waiting.querySelector('code')).toBeNull();

    const running = testing.querySelector('[data-stage="setl-web:unit1"]');
    expect(running.textContent).toContain('pipeline.testRunning');
    expect(running.textContent).toContain('25%');
    expect(running.querySelector('[data-count]').textContent).toBe(
      'pipeline.progressTests{"done":120,"total":480}',
    );
    expect(running.textContent).toContain('pipeline.failedCount{"count":2}');
    expect(running.querySelector('[data-profile="full"]').textContent).toBe('pipeline.profileFull');
    expect(running.querySelector('code').textContent).toBe('dt-gate-card-2-1');

    // A stage whose command counts nothing shows no count, never 0/0.
    const vet = testing.querySelector('[data-stage="setl:vet"]');
    expect(vet.querySelector('[data-count]')).toBeNull();
    expect(vet.textContent).not.toContain('%');

    const recent = [...testing.querySelectorAll('[data-recent-stage]')];
    expect(recent.map((row) => row.getAttribute('data-recent-stage'))).toEqual([
      'setl:race',
      'setl-web:unit2',
      'setl:unit',
    ]);
    expect(recent[0].querySelector('[data-result]').textContent).toBe('pipeline.resultFail');
    expect(recent[0].textContent).toContain(dur(12, 'm', 5, 's'));
    expect(recent[0].textContent).toContain(
      `pipeline.queuedPart{"duration":"${dur(2, 'm', 0, 's')}"}`,
    );
    expect(recent[0].textContent).toContain('pipeline.countTests{"count":812}');
    expect(recent[0].textContent).toContain('pipeline.failedCount{"count":3}');
    expect(recent[0].textContent).toContain('pipeline.attempts{"count":2}');
    expect(recent[1].querySelector('[data-result]').textContent).toBe('pipeline.resultOk');
    expect(recent[1].textContent).toContain('pipeline.flaky');
    // A stage that could not run carries why, on hover.
    expect(recent[2].querySelector('[data-result]').textContent).toBe('pipeline.resultError');
    expect(recent[2].querySelector('[title="could not start the container"]')).not.toBeNull();
    expect(testing.textContent).toContain('pipeline.recordedSince');
  });

  test('Testing: a stage name opens its card', async () => {
    await renderStrip();
    await openTab('testing');

    click(panel('testing').querySelector('[data-test-card="card-2"] button'));

    expect(dispatchedActions).toContainEqual({
      type: 'router-push',
      payload: { to: '/cards/card-2' },
    });
  });

  test('Deployment: a lane per repository with the deploy, its riders, the waiting cards and the last deploys', async () => {
    await renderStrip();
    await openTab('deployment');

    const deployment = panel('deployment');
    expect(
      [...deployment.querySelectorAll('[data-lane]')].map((lane) => lane.getAttribute('data-lane')),
    ).toEqual(['setl', 'setl-web']);

    const setl = deployment.querySelector('[data-lane="setl"]');
    const now = setl.querySelector('[data-deploying="card-d"]');
    expect(now.textContent).toContain('Deploying ticket');
    expect(now.textContent).toContain('60%');
    expect(now.querySelector('[data-job-state]').textContent).toBe(
      'pipeline.deployRunning{"thread":"CA2"}',
    );
    // Holding the lane for ten minutes.
    expect(now.textContent).toContain(dur(10, 'm', 0, 's'));
    expect(now.querySelector('[data-riders]').textContent).toContain('Rider one');
    expect(now.querySelector('[data-riders]').textContent).toContain('Rider two');

    const waiting = [...setl.querySelectorAll('[data-waiting]')];
    expect(waiting.map((row) => row.getAttribute('data-waiting'))).toEqual(['card-w1', 'card-w2']);
    expect(waiting[0].textContent).toContain('Very High');
    expect(waiting[0].textContent).toContain(dur(5, 'm', 0, 's'));
    expect(waiting[1].textContent).toContain(dur(20, 'm', 0, 's'));

    const runs = [...setl.querySelectorAll('[data-deploy-run]')];
    expect(runs.map((row) => row.querySelector('[data-result]').textContent)).toEqual([
      'pipeline.deployResultOk',
      'pipeline.deployResultNoResult',
    ]);
    expect(runs[0].textContent).toContain(dur(8, 'm', 0, 's'));
    expect(runs[1].textContent).toContain('pipeline.attempts{"count":2}');

    expect(deployment.querySelector('[data-lane="setl-web"]').textContent).toContain(
      'pipeline.deployIdle',
    );

    const redeploy = deployment.querySelector('[data-self-redeploy]');
    expect(redeploy.textContent).toContain(`pipeline.selfRedeploy{"age":"${dur(4, 'm', 0, 's')}"}`);
    expect(redeploy.textContent).toContain('Shipped');
  });

  test('Deployment: a deploy still waiting for a thread says so', async () => {
    const d = deploys();
    d.lanes[0].current = {
      ...d.lanes[0].current,
      jobState: 'waiting-thread',
      thread: undefined,
      progress: undefined,
    };
    d.selfRedeploy = undefined;
    getAnswer = () => jsonResponse(200, view({ deploys: d }));

    await renderStrip();
    await openTab('deployment');

    expect(panel('deployment').querySelector('[data-job-state]').textContent).toBe(
      'pipeline.deployWaitingThread{"thread":"—"}',
    );
    expect(panel('deployment').querySelector('[data-self-redeploy]')).toBeNull();
  });

  test('Accounts: usage windows with resets, the endpoint verdict, the limit and the reading age', async () => {
    await renderStrip();
    await openTab('accounts');

    const accountsPanel = panel('accounts');
    const a = accountsPanel.querySelector('[data-account="claude-a"]');
    expect(
      [...a.querySelectorAll('[data-window]')].map((w) => w.getAttribute('data-window')),
    ).toEqual(['5h', 'week', 'week_fable']);
    const fiveHour = a.querySelector('[data-window="5h"]');
    expect(fiveHour.textContent).toContain('42%');
    expect(fiveHour.textContent).toContain('pipeline.resetsIn');
    expect(fiveHour.textContent).toContain(`"duration":"${dur(2, 'h', 14, 'm')}"`);
    // A reset three days out carries its date.
    expect(a.querySelector('[data-window="week"]').textContent).toMatch(/27/);
    expect(a.querySelector('[data-endpoint-status]').textContent).toBe('pipeline.endpointWarning');
    expect(a.textContent).toContain(`pipeline.readingAge{"duration":"${dur(10, 'm', 0, 's')}"}`);
    expect(a.querySelector('[data-limited]')).toBeNull();

    const b = accountsPanel.querySelector('[data-account="claude-b"]');
    expect(b.querySelector('[data-limited]').textContent).toContain('pipeline.limitedUntil');
    expect(b.querySelector('[data-limited]').textContent).toContain(
      `"duration":"${dur(1, 'h', 0, 'm')}"`,
    );
    expect(b.textContent).toContain('pipeline.limitedNoThreads');
    expect(b.querySelector('[data-stale]').textContent).toContain('pipeline.readingStale');
    expect(b.querySelectorAll('[data-window]')).toHaveLength(0);

    const c = accountsPanel.querySelector('[data-account="claude-c"]');
    expect(c.textContent).toContain('pipeline.authApiKey');
    expect(c.textContent).toContain('pipeline.noUsageWindows');

    const d = accountsPanel.querySelector('[data-account="claude-d"]');
    expect(d.textContent).toContain('pipeline.authEndpoint{"host":"llm.example.com"}');
    expect(d.querySelector('[data-endpoint-status]').textContent).toBe('pipeline.endpointRefused');
    expect(d.querySelector('[data-window="5h"]').textContent).toContain('100%');

    // The tab itself carries the alarm while it is not open.
    expect(container.querySelector('[data-tab="accounts"]').textContent).toContain('⛔');
  });

  test("Testing and Accounts write dates and times in the viewer's Planka language, not the browser's", async () => {
    mockLanguage = 'de-DE';
    const nowMs = Date.parse(NOW);
    const [limited] = goldenView.accounts.filter((account) => account.limited);
    const weekReset = goldenView.accounts[0].windows.find((w) => w.key === 'week').resetsAt;

    // Each must read differently in German, or this test could not tell.
    expect(formatDay(goldenView.tests.recordedSince, 'de-DE')).not.toBe(
      formatDay(goldenView.tests.recordedSince, 'en-US'),
    );
    expect(formatWhen(weekReset, nowMs, 'de-DE')).not.toBe(formatWhen(weekReset, nowMs, 'en-US'));

    try {
      await renderStrip();
      await openTab('testing');

      expect(panel('testing').textContent).toContain(
        `pipeline.recordedSince{"date":"${formatDay(goldenView.tests.recordedSince, 'de-DE')}"}`,
      );

      await openTab('accounts');

      const accountsPanel = panel('accounts');
      expect(
        accountsPanel.querySelector('[data-account="claude-a"] [data-window="week"]').textContent,
      ).toContain(`"when":"${formatWhen(weekReset, nowMs, 'de-DE')}"`);
      expect(
        accountsPanel.querySelector(`[data-account="${limited.name}"] [data-limited]`).textContent,
      ).toContain(`"when":"${formatWhen(limited.limitedUntil, nowMs, 'de-DE')}"`);
      expect(
        accountsPanel.querySelector(`[data-account="${limited.name}"] [data-stale]`).textContent,
      ).toContain(`"when":"${formatWhen(limited.fetchedAt, nowMs, 'de-DE')}"`);
    } finally {
      mockLanguage = 'en-US';
    }
  });
});

describe('the header chips take you to their area', () => {
  let scrolledTo;
  const { scrollIntoView } = Element.prototype;

  const header = () => container.querySelector('[data-pipeline-strip="ok"] [role="button"]');
  const selectedTab = () => {
    const tab = container.querySelector('[role="tab"][aria-selected="true"]');
    return tab && tab.getAttribute('data-tab');
  };
  const scrolledSections = () => scrolledTo.map((element) => element.getAttribute('data-section'));

  const clickChip = async (name) => {
    click(container.querySelector(`[data-chip="${name}"]`));
    await flush();
  };

  beforeEach(() => {
    scrolledTo = [];
    // jsdom has none; the strip calls it on the section a chip names.
    Element.prototype.scrollIntoView = jest.fn(function record() {
      scrolledTo.push(this);
    });
  });

  afterEach(() => {
    Element.prototype.scrollIntoView = scrollIntoView;
  });

  test.each([
    ['threads', 'build', 'threads'],
    ['queue', 'build', 'queue'],
    ['paused', 'build', 'paused'],
    ['draining', 'build', 'controls'],
    ['tests', 'testing', 'none'],
    ['deploys', 'deployment', 'none'],
    ['limited', 'accounts', 'none'],
  ])(
    'the %s chip opens the collapsed strip on the %s tab (section: %s)',
    async (chip, tab, section) => {
      // Start on another tab, so landing on the chip's tab is the chip's doing.
      localStorage.setItem('planka_pipelineStrip_tab', tab === 'build' ? 'statistics' : 'build');

      await renderStrip();
      expect(header().getAttribute('aria-expanded')).toBe('false');

      await clickChip(chip);

      expect(header().getAttribute('aria-expanded')).toBe('true');
      expect(localStorage.getItem('planka_pipelineStrip_expanded')).toBe('true');
      expect(selectedTab()).toBe(tab);
      // Remembered the same as clicking the tab.
      expect(localStorage.getItem('planka_pipelineStrip_tab')).toBe(tab);

      if (tab === 'build') {
        expect(container.querySelector('[data-tab-panel]')).toBeNull();
      } else {
        expect(panel(tab)).not.toBeNull();
      }

      expect(scrolledSections()).toEqual(section === 'none' ? [] : [section]);
    },
  );

  test('the dispatch-held chip goes to the pause/resume pipeline controls', async () => {
    getAnswer = () => jsonResponse(200, view({ drain: { active: false }, dispatching: false }));

    await renderStrip();
    expect(container.querySelector('[data-chip="draining"]')).toBeNull();

    await clickChip('held');

    expect(selectedTab()).toBe('build');
    expect(scrolledSections()).toEqual(['controls']);
    expect(
      container.querySelector('[data-section="controls"] [data-action="drain-on"]'),
    ).not.toBeNull();
  });

  test('the queue chip opens the queue section and remembers it open', async () => {
    await renderStrip();

    await clickChip('queue');

    // Two of three threads busy: the rule keeps the queue shut, so opening it
    // is a choice worth remembering, as the section's own toggle does.
    const toggle = container.querySelector('[data-section="queue"] [aria-expanded]');
    expect(toggle.getAttribute('aria-expanded')).toBe('true');
    expect(container.querySelectorAll('[data-job]')).toHaveLength(3);
    expect(localStorage.getItem('planka_pipelineStrip_queueOpened')).toBe('true');
  });

  test('a chip for where you already are keeps the strip open instead of toggling it', async () => {
    localStorage.setItem('planka_pipelineStrip_expanded', 'true');
    localStorage.setItem('planka_pipelineStrip_tab', 'testing');

    await renderStrip();
    expect(selectedTab()).toBe('testing');

    await clickChip('tests');
    await clickChip('threads');
    await clickChip('threads');

    expect(header().getAttribute('aria-expanded')).toBe('true');
    expect(selectedTab()).toBe('build');
    // The same chip twice scrolls twice.
    expect(scrolledSections()).toEqual(['threads', 'threads']);
  });

  test('the empty header and the title still expand and collapse it', async () => {
    await renderStrip();

    click(header());
    await flush();
    expect(header().getAttribute('aria-expanded')).toBe('true');

    click(header().querySelector('span'));
    await flush();
    expect(header().getAttribute('aria-expanded')).toBe('false');
    expect(scrolledTo).toEqual([]);
  });

  test('chips are buttons: reachable by Tab, and Enter on one does not toggle the header', async () => {
    await renderStrip();

    const chips = [...container.querySelectorAll('[data-chip]')];
    expect(chips.map((chip) => chip.getAttribute('data-chip'))).toEqual([
      'threads',
      'queue',
      'paused',
      'draining',
      'tests',
      'deploys',
      'limited',
    ]);
    chips.forEach((chip) => {
      expect(chip.tagName).toBe('BUTTON');
      expect(chip.getAttribute('type')).toBe('button');
      expect(chip.className).toContain('chipButton');
    });
    // Each names where it goes, not the header's "expand".
    expect(chips.map((chip) => chip.getAttribute('title'))).toEqual([
      'pipeline.tabBuild',
      'pipeline.tabBuild',
      'pipeline.tabBuild',
      'pipeline.tabBuild',
      'pipeline.tabTesting',
      'pipeline.deploysChipTitle{"deploying":1,"waiting":2}',
      'pipeline.tabAccounts',
    ]);

    // A button turns Enter and Space into its own click; the header must not
    // also read the key as its own toggle.
    act(() => {
      chips[4].dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    });
    await flush();
    expect(header().getAttribute('aria-expanded')).toBe('false');

    act(() => {
      header().dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    });
    await flush();
    expect(header().getAttribute('aria-expanded')).toBe('true');
  });
});
